### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by 704408908** [Zakiaatot/my_wechat_gpt_bot#2]
What is the reason for displaying 'fetch failed'

**Comment by Zakiaatot** [comment]
Please ensure that your node version is above 18.

**Comment by 704408908** [comment]
My node version is already over 18, but when chatting, I still reply with 'fetch failed'

**Comment by Zakiaatot** [comment]
> My node version is already over 18, but when chatting, I still reply with 'fetch failed'
try this
[https://github.com/transitive-bullshit/chatgpt-api/issues/419](https://github.com/transitive-bullshit/chatgpt-api/issues/419)
