### ISSUE TITLE
fetch failed

### ISSUE THREAD

**Issue by StarkLiuyin** [Zakiaatot/my_wechat_gpt_bot#3]
机器人一直回复fetch failed、 fetch failed。。。咱办

**Comment by liujiafu1514** [comment]
同问，其他配置都好了，就这个问题一直无法解决

**Comment by Zakiaatot** [comment]
[看这个](https://github.com/Zakiaatot/my_wechat_gpt_bot/issues/2#issuecomment-1506273220)，然后确保机器不是openai的黑名单区域（如大陆），否则要vpn
